### ISSUE TITLE
Chunker error during start

### ISSUE THREAD

**Issue by dblas** [ZeroChaos-/blue_hydra#9]
Bravo for having continued the blue_hydra project.
I have the following errors during the start. 
A hint to solve it?

```
D, [2022-08-29T14:58:51.394960 #15949] DEBUG -- : Executing Command: hciconfig hci0
I, [2022-08-29T14:58:51.976326 #15949]  INFO -- : BlueHydra Starting...
D, [2022-08-29T14:58:51.976785 #15949] DEBUG -- : Runner starting with command: 'cat true' ...
I, [2022-08-29T14:58:51.986637 #15949]  INFO -- : No devices found in DB, starting clean.
I, [2022-08-29T14:58:51.987117 #15949]  INFO -- : Result thread starting
I, [2022-08-29T14:58:51.987772 #15949]  INFO -- : Parser thread starting
I, [2022-08-29T14:58:52.018551 #15949]  INFO -- : Chunker thread starting
I, [2022-08-29T14:58:52.019217 #15949]  INFO -- : Btmon thread starting
I, [2022-08-29T14:58:52.019720 #15949]  INFO -- : Command Line UI thread starting
E, [2022-08-29T14:58:52.053355 #15949] ERROR -- : Btmon thread exiting...
E, [2022-08-29T14:58:52.054779 #15949] ERROR -- : Chunker thread no implicit conversion of nil into String
E, [2022-08-29T14:58:52.055365 #15949] ERROR -- : /usr/lib/ruby/2.3.0/time.rb:363:in `_parse'
E, [2022-08-29T14:58:52.055601 #15949] ERROR -- : /usr/lib/ruby/2.3.0/time.rb:363:in `parse'
E, [2022-08-29T14:58:52.055775 #15949] ERROR -- : /home/pi/blue_hydra/lib/blue_hydra/chunker.rb:74:in `chunk_it_up'
E, [2022-08-29T14:58:52.055942 #15949] ERROR -- : /home/pi/blue_hydra/lib/blue_hydra/runner.rb:757:in `block (2 levels) in start_chunker_thread'
E, [2022-08-29T14:58:52.056110 #15949] ERROR -- : /home/pi/blue_hydra/lib/blue_hydra/runner.rb:750:in `loop'
E, [2022-08-29T14:58:52.056274 #15949] ERROR -- : /home/pi/blue_hydra/lib/blue_hydra/runner.rb:750:in `block in start_chunker_thread'
W, [2022-08-29T14:58:52.056478 #15949]  WARN -- : Restarting Chunker...
E, [2022-08-29T14:58:53.020980 #15949] ERROR -- : Thread failure: btmon_thread
I, [2022-08-29T14:58:53.046279 #15949]  INFO -- : Runner stopped. Exiting after clearing queue...
I, [2022-08-29T14:58:53.046741 #15949]  INFO -- : Queue clear! Exiting.
W, [2022-08-29T14:58:53.047123 #15949]  WARN -- : GOODBYE! ^_^
```
Thank you,
db

**Comment by ZeroChaos-** [comment]
I believer this has been fixed in the current release.

**Comment by dblas** [comment]
OK, will check soon.
Thx
db
